import os, time, webbrowser

from colorama import Fore, Style

print ('\n')
def res():
    print(Style.RESET_ALL)


os.system('clear')
print("                              ,:',:`,:'           ")
print('                           __||_||_||_||__        ')
print('                      ____["""""""""""""""]____   ')
print("                      \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                            ,:',:`,:'           ")
print('                         __||_||_||_||__        ')
print('                    ____["""""""""""""""]____   ')
print("                    \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                          ,:',:`,:'           ")
print('                       __||_||_||_||__        ')
print('                  ____["""""""""""""""]____   ')
print("                  \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                        ,:',:`,:'           ")
print('                     __||_||_||_||__        ')
print('                ____["""""""""""""""]____   ')
print("                \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                      ,:',:`,:'           ")
print('                   __||_||_||_||__        ')
print('              ____["""""""""""""""]____   ')
print("              \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                    ,:',:`,:'           ")
print('                 __||_||_||_||__        ')
print('            ____["""""""""""""""]____   ')
print("            \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                  ,:',:`,:'           ")
print('               __||_||_||_||__        ')
print('          ____["""""""""""""""]____   ')
print("          \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                ,:',:`,:'           ")
print('             __||_||_||_||__        ')
print('        ____["""""""""""""""]____   ')
print("        \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("              ,:',:`,:'           ")
print('           __||_||_||_||__        ')
print('      ____["""""""""""""""]____   ')
print("      \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("            ,:',:`,:'           ")
print('         __||_||_||_||__        ')
print('    ____["""""""""""""""]____   ')
print("    \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("          ,:',:`,:'           ")
print('       __||_||_||_||__        ')
print('  ____["""""""""""""""]____   ')
print("  \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("        ,:',:`,:'           ")
print('     __||_||_||_||__        ')
print('____["""""""""""""""]____   ')
print("\ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("      ,:',:`,:'           ")
print('   __||_||_||_||__        ')
print('__["""""""""""""""]____   ')
print("' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("    ,:',:`,:'           ")
print(' __||_||_||_||__        ')
print('["""""""""""""""]____   ')
print("'''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ,:',:`,:'           ")
print('_||_||_||_||__        ')
print('""""""""""""""]____   ')
print("'''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print(",:',:`,:'           ")
print('|_||_||_||__        ')
print('""""""""""""]____   ')
print("'SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("',:`,:'           ")
print('||_||_||__        ')
print('""""""""""]____   ')
print("SYPEXHACK''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print(":`,:'           ")
print('_||_||__        ')
print('""""""""]____   ')
print("SYPEXHACK''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print(",:'           ")
print('|_||__        ')
print('""""""]____   ')
print("SYPEXHACK' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("'           ")
print('||__        ')
print('""""]____   ')
print("SYPEXHACK\  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("          ")
print('__        ')
print('""]____   ')
print("SYPEXHACK ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("        ")
print('        ')
print(']____   ')
print("SYPEXHACK")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("      ")
print('      ')
print('___   ')
print("SYPEXHACK")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("    ")
print('    ')
print('_   ')
print("SYPEXHACK")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print('  ')
print('  ')
print("SYPEXHACK")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print('  ')
print('SYPEXHACK')
print("  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print('SYPEXHACK')
print('  ')
print("  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print('  SYPEXHACK')
print('  ')
print("  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print('    SYPEXHACK')
print('  ')
print("  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print('       SYPEXHACK')
print('  ')
print("  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print('         SYPEXHACK')
print('  ')
print("  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print('              SYPEXHACK')
print('  ')
print("  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("  ")
print(Fore.RED+'                 SYPEXHACK')
print(Fore.YELLOW+'                 telegram')
print("  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(3)

os.system('clear')
