import os, time, webbrowser

from colorama import Fore, Style

print ('\n')
def res():
    print(Style.RESET_ALL)


os.system('clear')
print("                              ,:',:`,:'           ")
print('                           __||_||_||_||__        ')
print('                      ____["""""""""""""""]____   ')
print("                      \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                            ,:',:`,:'           ")
print('                         __||_||_||_||__        ')
print('                    ____["""""""""""""""]____   ')
print("                    \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                          ,:',:`,:'           ")
print('                       __||_||_||_||__        ')
print('                  ____["""""""""""""""]____   ')
print("                  \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                        ,:',:`,:'           ")
print('                     __||_||_||_||__        ')
print('                ____["""""""""""""""]____   ')
print("                \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                      ,:',:`,:'           ")
print('                   __||_||_||_||__        ')
print('              ____["""""""""""""""]____   ')
print("              \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                    ,:',:`,:'           ")
print('                 __||_||_||_||__        ')
print('            ____["""""""""""""""]____   ')
print("            \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                  ,:',:`,:'           ")
print('               __||_||_||_||__        ')
print('          ____["""""""""""""""]____   ')
print("          \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("                ,:',:`,:'           ")
print('             __||_||_||_||__        ')
print('        ____["""""""""""""""]____   ')
print("        \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("              ,:',:`,:'           ")
print('           __||_||_||_||__        ')
print('      ____["""""""""""""""]____   ')
print("      \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("            ,:',:`,:'           ")
print('         __||_||_||_||__        ')
print('    ____["""""""""""""""]____   ')
print("    \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)
res()
os.system('clear')
print("          ,:',:`,:'           ")
print('       __||_||_||_||__        ')
print('  ____["""""""""""""""]____   ')
print("  \ ' '''''SYPEXHACK'''''' \  ")
print(Fore.BLUE+'~~^~~^~^~^~~^~^~^~~^~^~^^~^^~^~^~^~^~^~^~^~~^~^~^^')
time.sleep(0.3)

